# Generated by Django 5.1 on 2024-08-14 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bpmndiagram',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
